# Generated by Django 5.2.4 on 2025-07-29 07:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('practice_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('practice_website', models.CharField(blank=True, max_length=255, null=True)),
                ('practice_accrediation', models.CharField(blank=True, max_length=255, null=True)),
                ('social_media_links', models.JSONField(blank=True, null=True)),
                ('about_practice', models.TextField(blank=True, null=True)),
                ('facilities', models.JSONField(blank=True, null=True)),
                ('wheel_chair_access', models.BooleanField(blank=True, null=True)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('practice_location', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PractionerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PractionerRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practioner_name', models.CharField(max_length=255)),
                ('practioner_email', models.EmailField(max_length=255)),
                ('practioner_phone', models.CharField(max_length=255)),
                ('practioner_address', models.CharField(max_length=255)),
                ('practioner_city', models.CharField(max_length=255)),
                ('practioner_state', models.CharField(max_length=255)),
                ('practioner_zip', models.CharField(max_length=255)),
                ('practice_belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceapp.practiceregistry')),
            ],
        ),
    ]
