# Generated by Django 5.2.4 on 2025-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practioneruser',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='practioneruser',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='practioneruser',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
