# Generated by Django 5.2.4 on 2025-07-29 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0002_practioneruser_token_alter_practioneruser_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceregistry',
            name='practice_associated_with',
            field=models.CharField(default='asd', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practioneruser',
            name='practioner_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
