# Generated by Django 5.2.4 on 2025-07-30 08:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0003_practiceregistry_practice_associated_with_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('type_of_consultation', models.CharField(max_length=255)),
                ('patient_type', models.CharField(max_length=255)),
                ('patient_duration', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='practionerregistry',
            old_name='practioner_address',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='practionerregistry',
            old_name='practioner_city',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='practionerregistry',
            old_name='practioner_name',
            new_name='languages_spoken',
        ),
        migrations.RenameField(
            model_name='practionerregistry',
            old_name='practioner_phone',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='practionerregistry',
            old_name='practioner_state',
            new_name='qualifications',
        ),
        migrations.RemoveField(
            model_name='practionerregistry',
            name='practioner_email',
        ),
        migrations.RemoveField(
            model_name='practionerregistry',
            name='practioner_zip',
        ),
        migrations.AddField(
            model_name='practionerregistry',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='practionerregistry',
            name='link_to_best_practice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practionerregistry',
            name='professional_areas_of_interest',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practionerregistry',
            name='professional_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practionerregistry',
            name='appointments',
            field=models.ManyToManyField(blank=True, to='practiceapp.appointment'),
        ),
    ]
