# Generated by Django 5.2.4 on 2025-07-30 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0004_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceregistry',
            name='practice_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practiceapp.practioneruser'),
        ),
        migrations.AddField(
            model_name='practionerregistry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='practionerregistry',
            name='practitioner_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
