# Generated by Django 5.2.4 on 2025-08-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0006_availabilityslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practionerregistry',
            old_name='practice_belong_to',
            new_name='practiioner_belong_to',
        ),
    ]
