# Generated by Django 5.2.4 on 2025-08-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0007_rename_practice_belong_to_practionerregistry_practiioner_belong_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practionerregistry',
            old_name='practiioner_belong_to',
            new_name='practioner_belong_to',
        ),
    ]
