# Generated by Django 5.2.4 on 2025-08-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformuser', '0004_initial'),
        ('practiceapp', '0008_rename_practiioner_belong_to_practionerregistry_practioner_belong_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='AppointmentType',
        ),
    ]
