# Generated by Django 5.2.4 on 2025-08-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0009_rename_appointment_appointmenttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmenttype',
            old_name='patient_duration',
            new_name='appointment_patient_duration',
        ),
        migrations.RenameField(
            model_name='appointmenttype',
            old_name='patient_type',
            new_name='appointment_patient_type',
        ),
        migrations.RenameField(
            model_name='appointmenttype',
            old_name='is_enabled',
            new_name='is_appointment_enabled',
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='appointment_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
