# Generated by Django 5.2.4 on 2025-08-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0010_rename_patient_duration_appointmenttype_appointment_patient_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='STAFF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='practiceapp.practiceregistry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_of_practices', to='practiceapp.practioneruser')),
            ],
            options={
                'unique_together': {('practice', 'user')},
            },
        ),
    ]
