# Generated by Django 5.2.4 on 2025-08-05 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platformuser', '0003_remove_booking_slot_remove_booking_doctor_and_more'),
        ('practiceapp', '0007_rename_practice_belong_to_practionerregistry_practiioner_belong_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_booking_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booking_time', models.TimeField(blank=True, null=True)),
                ('booking_status', models.CharField(default='pending', max_length=255)),
                ('booking_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceapp.appointment')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceapp.practionerregistry')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformuser.patientuser')),
            ],
        ),
    ]
