# Generated by Django 5.2.4 on 2025-08-07 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformuser', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_family_member_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='patientuser',
            name='patient_family_members',
            field=models.ManyToManyField(blank=True, to='platformuser.patientfamilymember'),
        ),
    ]
