# Generated by Django 5.2.4 on 2025-08-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformuser', '0005_patientfamilymember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbooking',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='patientbooking',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='booking_slot',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
